spring:
  application:
    name: RESTAURANT-SERVICE
  config:
    import: optional:configserver:http://localhost:8888/config
  cloud:
    config:
     name: restaurant-service
     skip-ssl-validation: true
     force-pull: true